### ISSUE TITLE
How to cite this paper

### ISSUE THREAD

**Issue by deepdarkfans** [anonymized30/FL-Defender#1]
Hi, I am very interested in your research, but I found that the paper has not been accepted by the journal yet. Can you tell me how I should cite it?

**Comment by anonymized30** [comment]
Hi,
Currently, the paper is under review in a journal.
However, you could cite it using the citation below
@article{jebreel2022fl,
  title={FL-Defender: Combating Targeted Attacks in Federated Learning},
  author={Jebreel, Najeeb and Domingo-Ferrer, Josep},
  journal={arXiv preprint arXiv:2207.00872},
  year={2022}
}
Thank you!
